(lang dune 3.21)
(name lokto_webauthn_example)
(package
  (name lokto_webauthn_example)
  (depends
    ocaml
    lokto_webauthn
    dream
    crunch
    uuidm))
(pin
  (url "git+https://github.com/itswindtw/lokto_webauthn")
  (package
    (name lokto_webauthn)))
